//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookBidding
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSold
    {
        public int SaleId { get; set; }
        public string BookName { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    }
}
